TWITTER_ACCESS_TOKEN = "943056085-sm5YIHPJEofpWACCZm5Xk8GeJrsHCbX2rFvCxdTR"
TWITTER_ACCESS_TOKEN_SECRET = "ZCrLEiqDLGudNi4SqWxxowd1cHq1BNnKTwsvP49Sj2Ofh"
TWITTER_CONSUMER_KEY = "dalbN3rpD14BbVcgSBMmzbJpH"
TWITTER_CONSUMER_SECRET = "69fW72CeraXA7hAHJO4F0hVuuNApwueWVvFJ8qjHSPAsE2buDg"

ALPACA_ENDPOINT_URL = "https://paper-api.alpaca.markets"
ALPACA_API_KEY = "PK8L8DF42J3UG9SEUSFP"
ALPACA_SECRET_KEY = "x9CVJp3gwmDZ6cGEXyJs3t2PQxQzOvzYa7AHEEEN"
